# @package _global_

cuda: False

model_type: nn

trainer:
  _target_: src.trainers.NeuralNetworkTrainer
  early_stopping_metric: "val_loss"
  early_stopping_patience: 5_000
  n_optim_steps_min: 0
  n_optim_steps_max: 50_000
  n_samples_test: 100
  n_samples_train: 1
  n_validations: 500
  optimizer:
    _target_: torch.optim.SGD
    _partial_: True
    lr: 0.01
    weight_decay: 1e-4
  restore_best_model: True
  verbose: False